import { DSAuditConfig } from '../types';

export const defaultConfig: DSAuditConfig = {
  designSystemImports: [
    '@mui/material',
    '@mui/icons-material',
    '@company/ui',
    '@design-system/components',
  ],
  ignorePaths: [
    'node_modules',
    'dist',
    'build',
    'coverage',
    '.next',
    'out',
    'storybook-static',
    '.storybook',
  ],
  familyKeywords: [
    'button',
    'card',
    'modal',
    'input',
    'select',
    'badge',
    'tag',
    'alert',
    'dialog',
    'dropdown',
    'table',
    'tabs',
    'tab',
    'chip',
    'avatar',
    'icon',
    'link',
    'form',
    'list',
    'menu',
    'nav',
    'drawer',
    'popover',
    'tooltip',
    'spinner',
    'loader',
    'skeleton',
    'divider',
    'accordion',
    'breadcrumb',
    'pagination',
    'checkbox',
    'radio',
    'switch',
    'toggle',
    'slider',
    'textarea',
    'label',
    'text',
    'heading',
    'grid',
    'stack',
    'box',
    'container',
  ],
  penalties: {
    duplicateHigh: 25,
    duplicateMedium: 12,
    duplicateLow: 4,
    inlineStyle: 1.5,
    hardcodedColor: 2,
    hardcodedSpacing: 1,
  },
  bonuses: {
    approvedImport: 0.5,
  },
  scoreWeights: {
    approvedAdoption: 40,
    duplicateComponents: 20,
    tokenCompliance: 20,
    inlineStyles: 20,
  },
};
